### ISSUE TITLE
Creating ticket with attachments raised error if a `tags` field specified.

### ISSUE THREAD

**Issue by haiiiiiyun** [sjkingo/python-freshdesk#37] opened 2019-04-23 04:59 UTC

**Comment by sjkingo** [comment] 2019-04-23 08:22
Hi, are you able to provide a simple reproducible case and the complete output to show the error you're receiving?
Thanks

**Comment by sjkingo** [comment] 2020-01-31 04:02
Closing as unable to reproduce. Please open a new issue (or PR) if you come across it again. Thanks!

**Closed** 2020-01-31 04:02 UTC
